HomeManagement.AdminSite/Controllers/CurrencyController.cs
using HomeManagement.AdminSite.Filters;
using HomeManagement.AdminSite.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HomeManagement.AdminSite.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ICurrencyService currencyService;

        public CurrencyController(ICurrencyService currencyService)
        {
            this.currencyService = currencyService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currencies = await currencyService.GetCurrencies();
            return View(currencies);
        }
    }
}

HomeManagement.AdminSite/Controllers/HealthController.cs
using HomeManagement.AdminSite.Services;
using HomeManagement.Api.Core.HealthChecks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace HomeManagement.AdminSite.Controllers
{
    public class HealthController : Controller
    {
        private readonly HealthCheckService healthCheckService;
        private readonly IEndpointsHealthService endpointsHealthService;

        public HealthController(HealthCheckService healthCheckService, IEndpointsHealthService endpointsHealthService)
        {
            this.healthCheckService = healthCheckService;
            this.endpointsHealthService = endpointsHealthService;
        }

        public async Task<IActionResult> Index()
        {
            var models = new List<HealthReportModel>();
            models.AddRange(await endpointsHealthService.GetIdentityHealthReport());
            models.AddRange(await endpointsHealthService.GetApiHealthReport());
            models.AddRange(HealthReportModel.CreateFromReport(await healthCheckService.CheckHealthAsync(), "Admin"));

            return View(models);
        }

        public async Task<IActionResult> DownloadIdentityLogs()
        {
            var result = await endpointsHealthService.GetLogs("Identity");
            var stream = GenerateStreamFromString(result);
            return File(stream, "text/plain", "logs.txt");
        }

        public async Task<IActionResult> DownloadLogs()
        {
            var result = await endpointsHealthService.GetLogs("HomeManagement");
            var stream = GenerateStreamFromString(result);
            return File(stream, "text/plain", "logs.txt");
        }

        public Stream GenerateStreamFromString(string s)
        {
            MemoryStream stream = new MemoryStream();
            StreamWriter writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }
    }
}

HomeManagement.AdminSite/Controllers/PreferencesController.cs
using HomeManagement.Data;
using HomeManagement.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Linq;

namespace HomeManagement.AdminSite.Controllers
{
    public class PreferencesController : Controller
    {
        private readonly IMemoryCache _cache;
        private readonly IRepositoryFactory repositoryFactory;

        public PreferencesController(IRepositoryFactory repositoryFactory,
            IMemoryCache memoryCache)
        {
            _cache = memoryCache;
            this.repositoryFactory = repositoryFactory;
        }

        public IActionResult Index()
        {
            using (var preferencesRepository = repositoryFactory.CreatePreferencesRepository())
            using (var userRepository = repositoryFactory.CreateUserRepository())
            {
                var preferences = preferencesRepository.GetAll();

                var users = userRepository.GetAll();

                foreach (var p in preferences)
                {
                    var user = users.FirstOrDefault(x => x.Id.Equals(p.UserId));

                    if(user != null)
                    {
                        p.User = user;
                    }
                }

                return View(preferences);
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Preferences preference)
        {
            using (var preferencesRepository = repositoryFactory.CreatePreferencesRepository())
            using (var userRepository = repositoryFactory.CreateUserRepository())
            {
                preferencesRepository.Add(preference);
                preferencesRepository.Commit();

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue) return NotFound();
            using (var preferencesRepository = repositoryFactory.CreatePreferencesRepository())
            {
                var preference = preferencesRepository.GetById(id.Value);

                return View(preference);
            }
        }

        [HttpPost]
        public IActionResult Edit(Preferences preferences)
        {
            using (var preferencesRepository = repositoryFactory.CreatePreferencesRepository())
            {
                var entity = preferencesRepository.GetById(preferences.Id);

                entity.Value = preferences.Value;

                preferencesRepository.Update(entity);
                preferencesRepository.Commit();

                return RedirectToAction("Index");
            }
        }
    }
}

HomeManagement.AdminSite/Controllers/UsersController.cs
using HomeManagement.AdminSite.Services;
using HomeManagement.Models;
using HomeManagement.Core.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeManagement.AdminSite.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly IMemoryCache cache;

        public UsersController(IUserService userService, IMemoryCache cache)
        {
            this.userService = userService;
            this.cache = cache;
        }

        public async Task<IActionResult> Index()
        {
            return View(await GetUsers());
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id.IsEmpty()) return BadRequest();

            var users = await GetUsers();
            var userToDelete = users.First(x => x.Id.Equals(id));
            await userService.Delete(userToDelete.Email);
            FlushUserModels();
            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<UserIdentityModel>> GetUsers()
        {
            var users = cache.Get<IEnumerable<UserIdentityModel>>(nameof(GetUsers));

            if (users != null) return users;

            users = await userService.GetUsers();

            cache.CreateEntry(nameof(GetUsers));
            cache.Set(nameof(GetUsers), users, new MemoryCacheEntryOptions
            {
                SlidingExpiration = TimeSpan.FromMinutes(10)
            });

            return users;
        }

        private void FlushUserModels()
        {
            cache.Remove(nameof(GetUsers));
        }
    }
}

HomeManagement.AdminSite/Views/Shared/_Footer.cshtml
@{
    ViewData["Title"] = "_Footer";
}

<footer class="border-top footer text-muted">
    <div class="container">
    </div>
</footer>

HomeManagement.AdminSite/Views/Shared/_Header.cshtml
@using static HomeManagement.AdminSite.Views.RazorExtensions

@{
    ViewData["Title"] = "_Header";
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeManagement.AdminSite</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="ConfigurationSettings" asp-action="Index">Config Settings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="Currency" asp-action="Index">Currencies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="Users" asp-action="Index">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="UserCategories" asp-action="Index">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="Preferences" asp-action="Index">Preferences</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-host="@this.Context.GetHost()" asp-controller="Health" asp-action="Index">Health Report</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

HomeManagement.AdminSite/Views/Shared/_Layout.cshtml
@using static HomeManagement.AdminSite.Views.RazorExtensions

@{
    var path = this.Context.GetHeader("X-Forwarded-PathBase");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeManagement AdminSite</title>

    <environment include="Development">
        <link rel="stylesheet" href="@(path)/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="@(path)/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="@(path)/css/site.css" />
</head>
<body>
    @RenderBody()
    <environment include="Development">
        <script src="@(path)/lib/jquery/dist/jquery.js"></script>
        <script src="@(path)/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="@(path)/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="@(path)/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="@(path)/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>